import { MigrationInterface, QueryRunner } from "typeorm";

export class Changes1788109747859 implements MigrationInterface {
    name = 'Changes1788109747859'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "vendor_contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vendorId" uuid NOT NULL, "name" character varying NOT NULL, "designation" character varying NOT NULL, "address" character varying, "email" character varying, "phone" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_be85926efdfccb43c9fe0797799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client_rates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientId" uuid NOT NULL, "vehicleId" uuid NOT NULL, "cityId" integer NOT NULL, "price" numeric(10,2) NOT NULL, "effectiveFromDate" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1b03e2d061451d8e2779d5c3881" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client_rate_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientRateId" uuid NOT NULL, "previousPrice" numeric(10,2), "effectiveFromDate" date, "effectiveToDate" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5ba190dce6a00a31e5e4cb55d8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "warehouses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_56ae21ee2432b2270b48867e4be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assigned_vehicles_status_enum" AS ENUM('PENDING', 'ASSIGNED', 'UNASSIGNED')`);
        await queryRunner.query(`CREATE TABLE "assigned_vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverId" uuid NOT NULL, "vehicleId" uuid NOT NULL, "assignedDate" character varying, "status" "public"."assigned_vehicles_status_enum" NOT NULL DEFAULT 'PENDING', "name" character varying, "phone" character varying, "address" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_daec125155825c7dbfa49f646c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "vendors" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "vendors" ADD "joiningDate" character varying`);
        await queryRunner.query(`ALTER TABLE "vendors" ADD "ownerName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vendors" ADD "vendorName" character varying`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "vehicleImages" jsonb`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "joiningDate" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "ptclNo" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "saleTaxStatus" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "withHoldingTaxStatus" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "isWarehouseOwner" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "joiningDate" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "cnicNo" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "gurantorName" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "gurantorPhone" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "gurantorAddress" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "gurantorCNIC" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "avatar" character varying`);
        await queryRunner.query(`ALTER TABLE "bilty_loadings" ADD "noOfLoadingStops" integer`);
        await queryRunner.query(`ALTER TABLE "bilty_off_loadings" ADD "noOfOffLoadingStops" integer`);
        await queryRunner.query(`ALTER TYPE "public"."vehicles_ownership_enum" RENAME TO "vehicles_ownership_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_ownership_enum" AS ENUM('CONTRACT_BASED', 'BANK_LEASE', 'OWN', 'RENTED')`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "ownership" TYPE "public"."vehicles_ownership_enum" USING "ownership"::"text"::"public"."vehicles_ownership_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_ownership_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."vehicle_documents_doctype_enum" RENAME TO "vehicle_documents_doctype_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_documents_doctype_enum" AS ENUM('INSURANCE_CERTIFICATE', 'REGISTRATION_CARD', 'REGISTRATION_BOOK', 'CERTIFICATE_OF_FITNESS', 'TAX_CERTIFICATE', 'ROUTE_PERMIT', 'REGISTERATION', 'POLICE_VERIFICATION', 'TRACKER_CERTIFICATE', 'THIRD_PARTY_CERTIFICATE', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "vehicle_documents" ALTER COLUMN "docType" TYPE "public"."vehicle_documents_doctype_enum" USING "docType"::"text"::"public"."vehicle_documents_doctype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_documents_doctype_enum_old"`);
        await queryRunner.query(`ALTER TABLE "client_documents" ALTER COLUMN "file" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "client_documents" DROP CONSTRAINT "UQ_3452e7ead96feb85907cd0e4809"`);
        await queryRunner.query(`ALTER TABLE "client_documents" ALTER COLUMN "validity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."drivers_drivertype_enum" RENAME TO "drivers_drivertype_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."drivers_drivertype_enum" AS ENUM('HELPER', '1ST_DRIVER', '2ND_DRIVER')`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "driverType" TYPE "public"."drivers_drivertype_enum" USING "driverType"::"text"::"public"."drivers_drivertype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."drivers_drivertype_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."driver_documents_doctype_enum" RENAME TO "driver_documents_doctype_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."driver_documents_doctype_enum" AS ENUM('LICENSE', 'CNIC', 'GURANTOR_CNIC', 'POLICE_VERIFICATION', 'ELECTRICITY_BILL', 'MOTERWAY_CARD', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "driver_documents" ALTER COLUMN "docType" TYPE "public"."driver_documents_doctype_enum" USING "docType"::"text"::"public"."driver_documents_doctype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."driver_documents_doctype_enum_old"`);
        await queryRunner.query(`ALTER TABLE "driver_documents" ALTER COLUMN "file" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_documents" DROP CONSTRAINT "UQ_c85bd4070a3b910a4f7a2d358ce"`);
        await queryRunner.query(`ALTER TABLE "driver_documents" ALTER COLUMN "validity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."bilty_status_enum" RENAME TO "bilty_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."bilty_status_enum" AS ENUM('PENDING', 'APPROVED', 'CANCELLED', 'COMPLETED')`);
        await queryRunner.query(`ALTER TABLE "bilty" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "bilty" ALTER COLUMN "status" TYPE "public"."bilty_status_enum" USING "status"::"text"::"public"."bilty_status_enum"`);
        await queryRunner.query(`ALTER TABLE "bilty" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."bilty_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "vendor_contacts" ADD CONSTRAINT "FK_101dfd371f1b72280b0eb82e285" FOREIGN KEY ("vendorId") REFERENCES "vendors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_rates" ADD CONSTRAINT "FK_bcc804cedbff6f7043df5efcbf7" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_rates" ADD CONSTRAINT "FK_66fe1ca08d82662da21eed5cf01" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_rates" ADD CONSTRAINT "FK_c60e2f03fe0cfa42c8bb52356e4" FOREIGN KEY ("cityId") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_rate_logs" ADD CONSTRAINT "FK_b906880371a7fdc88b28d3461ab" FOREIGN KEY ("clientRateId") REFERENCES "client_rates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD CONSTRAINT "FK_23762382443115c3bdff867268d" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assigned_vehicles" ADD CONSTRAINT "FK_13f98e64dcd8b57e3550a226efc" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assigned_vehicles" ADD CONSTRAINT "FK_e928dbbe4359198aa686744bed6" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "assigned_vehicles" DROP CONSTRAINT "FK_e928dbbe4359198aa686744bed6"`);
        await queryRunner.query(`ALTER TABLE "assigned_vehicles" DROP CONSTRAINT "FK_13f98e64dcd8b57e3550a226efc"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP CONSTRAINT "FK_23762382443115c3bdff867268d"`);
        await queryRunner.query(`ALTER TABLE "client_rate_logs" DROP CONSTRAINT "FK_b906880371a7fdc88b28d3461ab"`);
        await queryRunner.query(`ALTER TABLE "client_rates" DROP CONSTRAINT "FK_c60e2f03fe0cfa42c8bb52356e4"`);
        await queryRunner.query(`ALTER TABLE "client_rates" DROP CONSTRAINT "FK_66fe1ca08d82662da21eed5cf01"`);
        await queryRunner.query(`ALTER TABLE "client_rates" DROP CONSTRAINT "FK_bcc804cedbff6f7043df5efcbf7"`);
        await queryRunner.query(`ALTER TABLE "vendor_contacts" DROP CONSTRAINT "FK_101dfd371f1b72280b0eb82e285"`);
        await queryRunner.query(`CREATE TYPE "public"."bilty_status_enum_old" AS ENUM('PENDING', 'APPROVED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "bilty" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "bilty" ALTER COLUMN "status" TYPE "public"."bilty_status_enum_old" USING "status"::"text"::"public"."bilty_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "bilty" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."bilty_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."bilty_status_enum_old" RENAME TO "bilty_status_enum"`);
        await queryRunner.query(`ALTER TABLE "driver_documents" ALTER COLUMN "validity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_documents" ADD CONSTRAINT "UQ_c85bd4070a3b910a4f7a2d358ce" UNIQUE ("file")`);
        await queryRunner.query(`ALTER TABLE "driver_documents" ALTER COLUMN "file" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."driver_documents_doctype_enum_old" AS ENUM('LICENSE', 'CNIC', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "driver_documents" ALTER COLUMN "docType" TYPE "public"."driver_documents_doctype_enum_old" USING "docType"::"text"::"public"."driver_documents_doctype_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."driver_documents_doctype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."driver_documents_doctype_enum_old" RENAME TO "driver_documents_doctype_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."drivers_drivertype_enum_old" AS ENUM('HELPER', 'FIRST_DRIVER', 'SECOND_DRIVER')`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "driverType" TYPE "public"."drivers_drivertype_enum_old" USING "driverType"::"text"::"public"."drivers_drivertype_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."drivers_drivertype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."drivers_drivertype_enum_old" RENAME TO "drivers_drivertype_enum"`);
        await queryRunner.query(`ALTER TABLE "client_documents" ALTER COLUMN "validity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "client_documents" ADD CONSTRAINT "UQ_3452e7ead96feb85907cd0e4809" UNIQUE ("file")`);
        await queryRunner.query(`ALTER TABLE "client_documents" ALTER COLUMN "file" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_documents_doctype_enum_old" AS ENUM('CERTIFICATE_OF_FITNESS', 'TAX_CERTIFICATE', 'ROUTE_PERMIT', 'REGISTERATION')`);
        await queryRunner.query(`ALTER TABLE "vehicle_documents" ALTER COLUMN "docType" TYPE "public"."vehicle_documents_doctype_enum_old" USING "docType"::"text"::"public"."vehicle_documents_doctype_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_documents_doctype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."vehicle_documents_doctype_enum_old" RENAME TO "vehicle_documents_doctype_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_ownership_enum_old" AS ENUM('CONTRACT_BASED', 'BANK_LEASE', 'OWN')`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "ownership" TYPE "public"."vehicles_ownership_enum_old" USING "ownership"::"text"::"public"."vehicles_ownership_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_ownership_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."vehicles_ownership_enum_old" RENAME TO "vehicles_ownership_enum"`);
        await queryRunner.query(`ALTER TABLE "bilty_off_loadings" DROP COLUMN "noOfOffLoadingStops"`);
        await queryRunner.query(`ALTER TABLE "bilty_loadings" DROP COLUMN "noOfLoadingStops"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "avatar"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "gurantorCNIC"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "gurantorAddress"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "gurantorPhone"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "gurantorName"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "cnicNo"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "joiningDate"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "isWarehouseOwner"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "withHoldingTaxStatus"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "saleTaxStatus"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "ptclNo"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "joiningDate"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "vehicleImages"`);
        await queryRunner.query(`ALTER TABLE "vendors" DROP COLUMN "vendorName"`);
        await queryRunner.query(`ALTER TABLE "vendors" DROP COLUMN "ownerName"`);
        await queryRunner.query(`ALTER TABLE "vendors" DROP COLUMN "joiningDate"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "vendors" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "assigned_vehicles"`);
        await queryRunner.query(`DROP TYPE "public"."assigned_vehicles_status_enum"`);
        await queryRunner.query(`DROP TABLE "warehouses"`);
        await queryRunner.query(`DROP TABLE "client_rate_logs"`);
        await queryRunner.query(`DROP TABLE "client_rates"`);
        await queryRunner.query(`DROP TABLE "vendor_contacts"`);
    }

}
