import { MigrationInterface, QueryRunner } from "typeorm";

export class HR1790144818587 implements MigrationInterface {
    name = 'HR1790144818587'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "trip_documents" DROP CONSTRAINT "FK_trip_documents_tripId"`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" DROP CONSTRAINT "FK_notification_recipients_notificationId"`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" DROP CONSTRAINT "FK_notification_recipients_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_groupKey"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_recipients_user_read"`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" DROP CONSTRAINT "UQ_notification_recipients_notification_user"`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "break_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "allowedMinutes" integer NOT NULL, "windowStart" TIME NOT NULL, "windowEnd" TIME NOT NULL, "allowMultipleBreaks" boolean NOT NULL DEFAULT true, "paid" boolean NOT NULL DEFAULT true, "excessDeductible" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_829eefa8c9f409c3834e5e42ab2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "requiredWorkMinutes" integer NOT NULL, "graceMinutes" integer NOT NULL DEFAULT '0', "breakPolicyId" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shift_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeId" uuid NOT NULL, "shiftId" uuid NOT NULL, "workDate" date NOT NULL, "scheduledStartAt" TIMESTAMP WITH TIME ZONE NOT NULL, "scheduledEndAt" TIMESTAMP WITH TIME ZONE NOT NULL, "policySnapshot" jsonb NOT NULL, CONSTRAINT "PK_7a78d24f38deedd9fe0ea19685c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeId" uuid NOT NULL, "shiftAssignmentId" uuid NOT NULL, "attendanceDate" date NOT NULL, "firstCheckIn" TIMESTAMP WITH TIME ZONE, "lastCheckOut" TIMESTAMP WITH TIME ZONE, "workedMinutes" integer NOT NULL DEFAULT '0', "allowedBreakMinutes" integer NOT NULL DEFAULT '0', "excessBreakMinutes" integer NOT NULL DEFAULT '0', "lateMinutes" integer NOT NULL DEFAULT '0', "earlyLeaveMinutes" integer NOT NULL DEFAULT '0', "shortfallMinutes" integer NOT NULL DEFAULT '0', "overtimeMinutes" integer NOT NULL DEFAULT '0', "provisionalDeductionMinutes" integer NOT NULL DEFAULT '0', "status" character varying NOT NULL, "calculationStatus" character varying NOT NULL, "calculationVersion" integer NOT NULL DEFAULT '1', CONSTRAINT "REL_29c92620fd9ad579ec8c8d78b9" UNIQUE ("shiftAssignmentId"), CONSTRAINT "PK_483ed97cd4cd43ab4a117516b69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_29c92620fd9ad579ec8c8d78b9" ON "attendances" ("shiftAssignmentId") `);
        await queryRunner.query(`CREATE TYPE "public"."attendance_events_type_enum" AS ENUM('CHECK_IN', 'CHECK_OUT')`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_events_reason_enum" AS ENUM('BREAK', 'PERSONAL', 'OFFICIAL_DUTY', 'SHIFT_END')`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_events_source_enum" AS ENUM('MOBILE', 'BIOMETRIC', 'ADMIN', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "attendance_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "attendanceId" uuid NOT NULL, "type" "public"."attendance_events_type_enum" NOT NULL, "reason" "public"."attendance_events_reason_enum", "occurredAt" TIMESTAMP WITH TIME ZONE NOT NULL, "receivedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "source" "public"."attendance_events_source_enum" NOT NULL, "deviceId" character varying, "idempotencyKey" character varying, "createdBy" uuid, CONSTRAINT "UQ_2537aea6b71c4e627b353492332" UNIQUE ("idempotencyKey"), CONSTRAINT "PK_8d7140035888f869932307395ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_sessions_type_enum" AS ENUM('WORK', 'BREAK', 'PERSONAL', 'OFFICIAL_DUTY')`);
        await queryRunner.query(`CREATE TABLE "attendance_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "attendanceId" uuid NOT NULL, "type" "public"."attendance_sessions_type_enum" NOT NULL, "startAt" TIMESTAMP WITH TIME ZONE NOT NULL, "endAt" TIMESTAMP WITH TIME ZONE NOT NULL, "durationMinutes" integer NOT NULL, "eligibleMinutes" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_84d565d9e484e2bcdaf4a9e1890" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance_adjustments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "attendanceId" uuid NOT NULL, "originalEventId" uuid, "oldValue" jsonb, "newValue" jsonb NOT NULL, "reason" text NOT NULL, "requestedBy" uuid NOT NULL, "approvedBy" uuid, "status" character varying NOT NULL, CONSTRAINT "PK_64e302a0138736bfc1d8a436dfa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "gender"`);
        await queryRunner.query(`DROP TYPE "public"."employees_gender_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "maritalStatus"`);
        await queryRunner.query(`DROP TYPE "public"."employees_maritalstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."employees_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "emergencyContactRelation"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "taxNumber"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "dateOfBirth"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "joiningDate"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "altPhone"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "cnicNo"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "zip"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "photograph"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "bankName"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "bankAccountNumber"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "bankAccountTitle"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "emergencyContactName"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "emergencyContactPhone"`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "departmentId" uuid`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "attendanceEnabled" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "UQ_notifications_eventKey"`);
        await queryRunner.query(`CREATE INDEX "IDX_7a4bcfe446386dfd2319ca352d" ON "notifications" ("groupKey") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b0a45493af7d9873175eee482b" ON "notifications" ("eventKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_98f2bccc736607e4cb36807d16" ON "notification_recipients" ("userId", "readAt") `);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ADD CONSTRAINT "UQ_53cfd1bfedccc676fd6d74137bb" UNIQUE ("notificationId", "userId")`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_4edfe103ebf2fcb98dbb582554b" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_documents" ADD CONSTRAINT "FK_ecb4a4adc4e815c00dd94185467" FOREIGN KEY ("tripId") REFERENCES "trips"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ADD CONSTRAINT "FK_234adaa36f97dd1b2bd3a22d65b" FOREIGN KEY ("notificationId") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ADD CONSTRAINT "FK_452385a8220b8053ab65317ffa6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_9813dae2548b69a8fe6be5b8790" FOREIGN KEY ("breakPolicyId") REFERENCES "break_policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" ADD CONSTRAINT "FK_5a3da3ffc7e3502cfeab212b043" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" ADD CONSTRAINT "FK_647779813dec7e65a4f57bf878f" FOREIGN KEY ("shiftId") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_4a9f77d05b9c764ff1053401cdd" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_29c92620fd9ad579ec8c8d78b98" FOREIGN KEY ("shiftAssignmentId") REFERENCES "shift_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_events" ADD CONSTRAINT "FK_b8e2a2d4e8fcc0c192023403e9a" FOREIGN KEY ("attendanceId") REFERENCES "attendances"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_sessions" ADD CONSTRAINT "FK_14e826548aa5724af0c4a2cc4eb" FOREIGN KEY ("attendanceId") REFERENCES "attendances"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attendance_sessions" DROP CONSTRAINT "FK_14e826548aa5724af0c4a2cc4eb"`);
        await queryRunner.query(`ALTER TABLE "attendance_events" DROP CONSTRAINT "FK_b8e2a2d4e8fcc0c192023403e9a"`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_29c92620fd9ad579ec8c8d78b98"`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_4a9f77d05b9c764ff1053401cdd"`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" DROP CONSTRAINT "FK_647779813dec7e65a4f57bf878f"`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" DROP CONSTRAINT "FK_5a3da3ffc7e3502cfeab212b043"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_9813dae2548b69a8fe6be5b8790"`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" DROP CONSTRAINT "FK_452385a8220b8053ab65317ffa6"`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" DROP CONSTRAINT "FK_234adaa36f97dd1b2bd3a22d65b"`);
        await queryRunner.query(`ALTER TABLE "trip_documents" DROP CONSTRAINT "FK_ecb4a4adc4e815c00dd94185467"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_4edfe103ebf2fcb98dbb582554b"`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" DROP CONSTRAINT "UQ_53cfd1bfedccc676fd6d74137bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98f2bccc736607e4cb36807d16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0a45493af7d9873175eee482b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a4bcfe446386dfd2319ca352d"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "UQ_notifications_eventKey" UNIQUE ("eventKey")`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "attendanceEnabled"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "departmentId"`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "emergencyContactPhone" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "emergencyContactName" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "bankAccountTitle" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "bankAccountNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "bankName" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "photograph" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "zip" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "state" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "city" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "cnicNo" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "altPhone" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "joiningDate" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "dateOfBirth" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "taxNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "emergencyContactRelation" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."employees_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'TERMINATED', 'RESIGNED')`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "status" "public"."employees_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`CREATE TYPE "public"."employees_maritalstatus_enum" AS ENUM('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'SEPARATED')`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "maritalStatus" "public"."employees_maritalstatus_enum" NOT NULL DEFAULT 'SINGLE'`);
        await queryRunner.query(`CREATE TYPE "public"."employees_gender_enum" AS ENUM('MALE', 'FEMALE', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "gender" "public"."employees_gender_enum" NOT NULL DEFAULT 'MALE'`);
        await queryRunner.query(`DROP TABLE "attendance_adjustments"`);
        await queryRunner.query(`DROP TABLE "attendance_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_sessions_type_enum"`);
        await queryRunner.query(`DROP TABLE "attendance_events"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_events_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_events_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_events_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29c92620fd9ad579ec8c8d78b9"`);
        await queryRunner.query(`DROP TABLE "attendances"`);
        await queryRunner.query(`DROP TABLE "shift_assignments"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP TABLE "break_policies"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ADD CONSTRAINT "UQ_notification_recipients_notification_user" UNIQUE ("notificationId", "userId")`);
        await queryRunner.query(`CREATE INDEX "IDX_notification_recipients_user_read" ON "notification_recipients" ("readAt", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_groupKey" ON "notifications" ("groupKey") `);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ADD CONSTRAINT "FK_notification_recipients_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ADD CONSTRAINT "FK_notification_recipients_notificationId" FOREIGN KEY ("notificationId") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_documents" ADD CONSTRAINT "FK_trip_documents_tripId" FOREIGN KEY ("tripId") REFERENCES "trips"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
