import { MigrationInterface, QueryRunner } from "typeorm";

export class MM1790409743120 implements MigrationInterface {
    name = 'MM1790409743120'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "brokers" DROP CONSTRAINT "FK_brokers_stateId"`);
        await queryRunner.query(`ALTER TABLE "brokers" DROP CONSTRAINT "FK_brokers_cityId"`);
        await queryRunner.query(`ALTER TABLE "broker_contacts" DROP CONSTRAINT "FK_broker_contacts_brokerId"`);
        await queryRunner.query(`ALTER TABLE "broker_documents" DROP CONSTRAINT "FK_broker_documents_brokerId"`);
        await queryRunner.query(`ALTER TABLE "transporters" DROP CONSTRAINT "FK_transporters_stateId"`);
        await queryRunner.query(`ALTER TABLE "transporters" DROP CONSTRAINT "FK_transporters_cityId"`);
        await queryRunner.query(`ALTER TABLE "transporter_contacts" DROP CONSTRAINT "FK_transporter_contacts_transporterId"`);
        await queryRunner.query(`ALTER TABLE "transporter_documents" DROP CONSTRAINT "FK_transporter_documents_transporterId"`);
        await queryRunner.query(`ALTER TABLE "bilty" DROP CONSTRAINT "FK_bilty_brokerId"`);
        await queryRunner.query(`ALTER TABLE "bilty" DROP CONSTRAINT "FK_bilty_transporterId"`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" DROP CONSTRAINT "FK_bilty_freights_biltyId"`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" DROP CONSTRAINT "FK_bilty_freights_brokerId"`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" DROP CONSTRAINT "FK_bilty_freights_assetAccId"`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" DROP CONSTRAINT "FK_bilty_freights_createdBy"`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_schedules_triggertype_enum" AS ENUM('odometer', 'time', 'odometer_or_time')`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_schedules_timeintervalunit_enum" AS ENUM('days', 'months', 'years')`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_schedules_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "maintenance_schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicleId" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text, "triggerType" "public"."maintenance_schedules_triggertype_enum" NOT NULL, "odometerInterval" numeric(12,2), "lastServiceOdometer" numeric(12,2), "nextDueOdometer" numeric(12,2), "odometerAlertBefore" numeric(12,2), "timeInterval" integer, "timeIntervalUnit" "public"."maintenance_schedules_timeintervalunit_enum", "lastServiceDate" TIMESTAMP, "nextDueDate" TIMESTAMP, "alertDaysBefore" integer, "status" "public"."maintenance_schedules_status_enum" NOT NULL DEFAULT 'active', "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2ce3383b6ff08ab48a28f515e4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."job_cards_maintenancetype_enum" AS ENUM('scheduled', 'unplanned')`);
        await queryRunner.query(`CREATE TYPE "public"."job_cards_priority_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."job_cards_status_enum" AS ENUM('draft', 'open', 'in_progress', 'on_hold', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "job_cards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jobCardNo" character varying(50) NOT NULL, "vehicleId" uuid NOT NULL, "driverId" uuid, "odometerReading" numeric(12,2) NOT NULL, "jobCardTitle" character varying(255) NOT NULL, "maintenanceType" "public"."job_cards_maintenancetype_enum" NOT NULL, "priority" "public"."job_cards_priority_enum" NOT NULL DEFAULT 'medium', "status" "public"."job_cards_status_enum" NOT NULL DEFAULT 'draft', "reportedById" uuid, "reportedAt" TIMESTAMP, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "cancelledAt" TIMESTAMP, "cancellationReason" text, "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "maintenanceScheduleId" uuid, CONSTRAINT "UQ_cdcb6c3413922a2848ad82cc60d" UNIQUE ("jobCardNo"), CONSTRAINT "PK_4810b52d9df46e7ef0d41beffe3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."job_card_items_status_enum" AS ENUM('open', 'in_progress', 'resolved', 'deferred', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "job_card_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jobCardId" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text, "status" "public"."job_card_items_status_enum" NOT NULL DEFAULT 'open', "resolutionNotes" text, "resolvedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_32b8e71e3f2570011f5f49a6acd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_quotations_status_enum" AS ENUM('draft', 'submitted', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "purchase_quotations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quotationNo" character varying(50) NOT NULL, "jobCardId" uuid, "vendorId" uuid NOT NULL, "vendorQuotationNo" character varying(100), "quotationDate" date NOT NULL, "validUntil" date, "subTotal" numeric(15,2) NOT NULL DEFAULT '0', "discountAmount" numeric(15,2) NOT NULL DEFAULT '0', "taxAmount" numeric(15,2) NOT NULL DEFAULT '0', "grandTotal" numeric(15,2) NOT NULL DEFAULT '0', "status" "public"."purchase_quotations_status_enum" NOT NULL DEFAULT 'draft', "termsAndConditions" text, "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7360b3cf281235cba204927317e" UNIQUE ("quotationNo"), CONSTRAINT "PK_92b2b397a788a1013a508ca5488" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_quotation_items_itemtype_enum" AS ENUM('product', 'service')`);
        await queryRunner.query(`CREATE TABLE "purchase_quotation_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseQuotationId" uuid NOT NULL, "itemType" "public"."purchase_quotation_items_itemtype_enum" NOT NULL, "productId" uuid, "itemName" character varying(255) NOT NULL, "description" text, "quantity" numeric(12,2) NOT NULL DEFAULT '1', "unitPrice" numeric(15,2) NOT NULL, "totalAmount" numeric(15,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a532500070b8d3c171f91bce2ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shop" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shopName" character varying NOT NULL, "ownerName" character varying NOT NULL, "ownerPhone" character varying NOT NULL, "branchCode" character varying NOT NULL, "address" character varying, "state" character varying, "city" character varying, "lat" character varying, "lng" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_57e39cec9b7d391feab2aa5c15a" UNIQUE ("branchCode"), CONSTRAINT "PK_ad47b7c6121fe31cb4b05438e44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."employee_salaries_paytype_enum" AS ENUM('MONTHLY', 'DAILY', 'HOURLY')`);
        await queryRunner.query(`CREATE TABLE "employee_salaries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeId" uuid NOT NULL, "payType" "public"."employee_salaries_paytype_enum" NOT NULL DEFAULT 'MONTHLY', "basicSalary" numeric(20,2) NOT NULL DEFAULT '0', "houseAllowance" numeric(20,2) NOT NULL DEFAULT '0', "transportAllowance" numeric(20,2) NOT NULL DEFAULT '0', "mobileAllowance" numeric(20,2) NOT NULL DEFAULT '0', "mealAllowance" numeric(20,2) NOT NULL DEFAULT '0', "otherAllowance" numeric(20,2) NOT NULL DEFAULT '0', "overtimeRatePerHour" numeric(20,2), "effectiveFrom" date NOT NULL, "effectiveTo" date, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fd1df358dabc2d3666d64e45d03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9b997acd6c774eb3fbff2aa35" ON "employee_salaries" ("employeeId", "effectiveFrom") `);
        await queryRunner.query(`CREATE TYPE "public"."pay_periods_status_enum" AS ENUM('OPEN', 'LOCKED', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "pay_periods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "status" "public"."pay_periods_status_enum" NOT NULL DEFAULT 'OPEN', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1eb133b5947dd46710dc78b94d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b5999386b61122bfeb6f7b748d" ON "pay_periods" ("startDate", "endDate") `);
        await queryRunner.query(`CREATE TYPE "public"."payroll_runs_status_enum" AS ENUM('DRAFT', 'CALCULATED', 'APPROVED', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "payroll_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payPeriodId" uuid NOT NULL, "status" "public"."payroll_runs_status_enum" NOT NULL DEFAULT 'DRAFT', "calculatedAt" TIMESTAMP WITH TIME ZONE, "approvedAt" TIMESTAMP WITH TIME ZONE, "approvedBy" uuid, "createdBy" uuid, "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6049f42c972640c0eb99ba8035e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payslips_status_enum" AS ENUM('DRAFT', 'FINALIZED', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "payslips" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payrollRunId" uuid NOT NULL, "employeeId" uuid NOT NULL, "employeeSalaryId" uuid, "basicSalary" numeric(20,2) NOT NULL DEFAULT '0', "houseAllowance" numeric(20,2) NOT NULL DEFAULT '0', "transportAllowance" numeric(20,2) NOT NULL DEFAULT '0', "mobileAllowance" numeric(20,2) NOT NULL DEFAULT '0', "mealAllowance" numeric(20,2) NOT NULL DEFAULT '0', "otherAllowance" numeric(20,2) NOT NULL DEFAULT '0', "overtimeMinutes" integer NOT NULL DEFAULT '0', "overtimeAmount" numeric(20,2) NOT NULL DEFAULT '0', "presentDays" integer NOT NULL DEFAULT '0', "absentDays" integer NOT NULL DEFAULT '0', "unpaidLeaveDays" integer NOT NULL DEFAULT '0', "paidLeaveDays" integer NOT NULL DEFAULT '0', "holidayDays" integer NOT NULL DEFAULT '0', "workedMinutes" integer NOT NULL DEFAULT '0', "lateMinutes" integer NOT NULL DEFAULT '0', "shortfallMinutes" integer NOT NULL DEFAULT '0', "attendanceDeductionAmount" numeric(20,2) NOT NULL DEFAULT '0', "otherDeductionAmount" numeric(20,2) NOT NULL DEFAULT '0', "grossAmount" numeric(20,2) NOT NULL DEFAULT '0', "totalDeductions" numeric(20,2) NOT NULL DEFAULT '0', "netAmount" numeric(20,2) NOT NULL DEFAULT '0', "status" "public"."payslips_status_enum" NOT NULL DEFAULT 'DRAFT', "salaryVoucherId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2b1cd07059daf60cc440c9976e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ee5bae81f62c8855325c8d6275" ON "payslips" ("payrollRunId", "employeeId") `);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_receivingstatus_enum" AS ENUM('not_received', 'partially_received', 'received')`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseOrderNo" character varying(50) NOT NULL, "purchaseQuotationId" uuid NOT NULL, "vendorId" uuid NOT NULL, "orderDate" date NOT NULL, "expectedDeliveryDate" date, "subTotal" numeric(15,2) NOT NULL DEFAULT '0', "discountAmount" numeric(15,2) NOT NULL DEFAULT '0', "taxAmount" numeric(15,2) NOT NULL DEFAULT '0', "grandTotal" numeric(15,2) NOT NULL DEFAULT '0', "status" "public"."purchase_orders_status_enum" NOT NULL DEFAULT 'draft', "receivingStatus" "public"."purchase_orders_receivingstatus_enum" NOT NULL DEFAULT 'not_received', "approvedById" uuid, "approvedAt" TIMESTAMP, "remarks" text, "termsAndConditions" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bccab167c9d217918e6032da774" UNIQUE ("purchaseOrderNo"), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_order_items_itemtype_enum" AS ENUM('product', 'service')`);
        await queryRunner.query(`CREATE TABLE "purchase_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseOrderId" uuid NOT NULL, "itemType" "public"."purchase_order_items_itemtype_enum" NOT NULL, "productId" uuid, "itemName" character varying(255) NOT NULL, "description" text, "quantity" numeric(12,2) NOT NULL, "unitPrice" numeric(15,2) NOT NULL, "totalAmount" numeric(15,2) NOT NULL, "receivedQuantity" numeric(12,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e8b7568d25c41e3290db596b312" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."goods_receipt_notes_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "goods_receipt_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "grnNo" character varying(50) NOT NULL, "purchaseOrderId" uuid NOT NULL, "receivedAt" TIMESTAMP NOT NULL, "receivedById" uuid, "vendorDocumentNo" character varying(100), "status" "public"."goods_receipt_notes_status_enum" NOT NULL DEFAULT 'draft', "approvedById" uuid, "approvedAt" TIMESTAMP, "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7ff28230480ac7953f57a9b4387" UNIQUE ("grnNo"), CONSTRAINT "PK_1cec586a0a55f192ee26bc5c3ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "goods_receipt_note_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "grnId" uuid NOT NULL, "productId" uuid NOT NULL, "purchaseOrderItemId" uuid NOT NULL, "receivedQuantity" numeric(12,2) NOT NULL, "rejectedQuantity" numeric(12,2) NOT NULL DEFAULT '0', "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_486fb6ccd950f71178b860c3b57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "maintenance_inventory_stocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "quantityOnHand" integer NOT NULL DEFAULT '0', "reservedQuantity" integer NOT NULL DEFAULT '0', "damagedQuantity" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f35b72258bedbe54f300db28b57" UNIQUE ("productId"), CONSTRAINT "PK_be4a62cead6c297e78c23e5fcac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_inventory_batches_status_enum" AS ENUM('active', 'depleted', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "maintenance_inventory_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "batchNo" character varying(50) NOT NULL, "receivedQuantity" integer NOT NULL, "availableQuantity" integer NOT NULL, "unitCost" numeric(15,2), "manufacturingDate" date, "expiryDate" date, "status" "public"."maintenance_inventory_batches_status_enum" NOT NULL DEFAULT 'active', "grnId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3475988e3910eef192df79e84e9" UNIQUE ("batchNo"), CONSTRAINT "PK_e7db059867c83e14b2eec294456" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_stock_logs_movementtype_enum" AS ENUM('in', 'out', 'adjustment_in', 'adjustment_out')`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_stock_logs_referencetype_enum" AS ENUM('grn', 'job_card', 'adjustment')`);
        await queryRunner.query(`CREATE TABLE "maintenance_stock_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "batchId" uuid, "movementType" "public"."maintenance_stock_logs_movementtype_enum" NOT NULL, "referenceType" "public"."maintenance_stock_logs_referencetype_enum" NOT NULL, "quantity" integer NOT NULL, "quantityBefore" integer NOT NULL, "quantityAfter" integer NOT NULL, "grnId" uuid, "jobCardId" uuid, "performedById" uuid, "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_840fb709ee10cbd361c8b8145bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_stock_issues_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "maintenance_stock_issues" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "issueNo" character varying(50) NOT NULL, "jobCardId" uuid NOT NULL, "issueDate" TIMESTAMP NOT NULL, "issuedById" uuid, "status" "public"."maintenance_stock_issues_status_enum" NOT NULL DEFAULT 'draft', "approvedById" uuid, "approvedAt" TIMESTAMP, "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_efbfd44f2df4f453f51f25d6736" UNIQUE ("issueNo"), CONSTRAINT "PK_508af431b120593d23cccef090e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "maintenance_stock_issue_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stockIssueId" uuid NOT NULL, "productId" uuid NOT NULL, "batchId" uuid NOT NULL, "quantity" numeric(15,2) NOT NULL, "unitCost" numeric(15,2), "totalCost" numeric(15,2), "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bfe6a5a3711ae7912a635f0ddb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TYPE "public"."activities_module_enum" RENAME TO "activities_module_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."activities_module_enum" AS ENUM('USERS_ACCESS', 'FINANCE', 'BILLING', 'TRIPS', 'MARKETPLACE', 'MAINTENANCE')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "module" TYPE "public"."activities_module_enum" USING "module"::"text"::"public"."activities_module_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activities_module_enum_old"`);
        await queryRunner.query(`ALTER TABLE "maintenance_schedules" ADD CONSTRAINT "FK_03aa43143cfbe07ac42b061837e" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_cards" ADD CONSTRAINT "FK_6c60830f6949223bab63f3c6934" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_cards" ADD CONSTRAINT "FK_c7ac66f7c358f2a13d7f883f7ba" FOREIGN KEY ("driverId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_cards" ADD CONSTRAINT "FK_f08a577bfd99d43be799fab0137" FOREIGN KEY ("reportedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_cards" ADD CONSTRAINT "FK_2b22db22210e8c93a93f79d6259" FOREIGN KEY ("maintenanceScheduleId") REFERENCES "maintenance_schedules"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_card_items" ADD CONSTRAINT "FK_5e2f6c1e2dc6351d5233a659c15" FOREIGN KEY ("jobCardId") REFERENCES "job_cards"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_quotations" ADD CONSTRAINT "FK_8121bfe95b8786437223d9972e5" FOREIGN KEY ("jobCardId") REFERENCES "job_cards"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_quotations" ADD CONSTRAINT "FK_20909dfcb24e8f531b21b2a2021" FOREIGN KEY ("vendorId") REFERENCES "vendors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_quotation_items" ADD CONSTRAINT "FK_46b622fbc48deb7fc11b7c50310" FOREIGN KEY ("purchaseQuotationId") REFERENCES "purchase_quotations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_quotation_items" ADD CONSTRAINT "FK_3957498131756bb07ceba105bcd" FOREIGN KEY ("productId") REFERENCES "vendor_products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brokers" ADD CONSTRAINT "FK_189811cc51835aff7c3ea909bde" FOREIGN KEY ("stateId") REFERENCES "states"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brokers" ADD CONSTRAINT "FK_c8a80dcab51a56e2cfa12b7eca8" FOREIGN KEY ("cityId") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "broker_contacts" ADD CONSTRAINT "FK_2065bfdccb7a129fb9eda24b920" FOREIGN KEY ("brokerId") REFERENCES "brokers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "broker_documents" ADD CONSTRAINT "FK_8d568802ba4d4a9d2781ea4ed9f" FOREIGN KEY ("brokerId") REFERENCES "brokers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transporters" ADD CONSTRAINT "FK_ba965a1211e126539bf77853e82" FOREIGN KEY ("stateId") REFERENCES "states"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transporters" ADD CONSTRAINT "FK_991bb6962884628500d9976025c" FOREIGN KEY ("cityId") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transporter_contacts" ADD CONSTRAINT "FK_0f239b0dfa61da1d289e8f6d39e" FOREIGN KEY ("transporterId") REFERENCES "transporters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transporter_documents" ADD CONSTRAINT "FK_572d7d58fb3f677dd9697f55ac5" FOREIGN KEY ("transporterId") REFERENCES "transporters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bilty" ADD CONSTRAINT "FK_42830f58f73360cfd463791c89a" FOREIGN KEY ("brokerId") REFERENCES "brokers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bilty" ADD CONSTRAINT "FK_b0cb3614189b98c4190781025a0" FOREIGN KEY ("transporterId") REFERENCES "transporters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" ADD CONSTRAINT "FK_2fac4cf52da3eefb6be1c0dc721" FOREIGN KEY ("biltyId") REFERENCES "bilty"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" ADD CONSTRAINT "FK_85e980ff939978db60fa5f47bee" FOREIGN KEY ("brokerId") REFERENCES "brokers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" ADD CONSTRAINT "FK_413f2d2b3e6f33e39bb457e239b" FOREIGN KEY ("assetAccId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" ADD CONSTRAINT "FK_cb771ce65ed39c4e6386e23f540" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_salaries" ADD CONSTRAINT "FK_9be022bd97dc15ebf40b2d813fa" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_runs" ADD CONSTRAINT "FK_21db0d0b704577d5831f603c9f9" FOREIGN KEY ("payPeriodId") REFERENCES "pay_periods"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_runs" ADD CONSTRAINT "FK_286ecf1480ead4f864cccf944c6" FOREIGN KEY ("approvedBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_runs" ADD CONSTRAINT "FK_a88d63ececef4f91cc8bc6f2d14" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payslips" ADD CONSTRAINT "FK_900143f20e6cd2fc0153db2242c" FOREIGN KEY ("payrollRunId") REFERENCES "payroll_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payslips" ADD CONSTRAINT "FK_3fa0aa64d0a6d751ea49e6cd804" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payslips" ADD CONSTRAINT "FK_6d014f9140e2573b815c9ea5f13" FOREIGN KEY ("employeeSalaryId") REFERENCES "employee_salaries"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payslips" ADD CONSTRAINT "FK_228a2b9d8338c0b6f02f314faa7" FOREIGN KEY ("salaryVoucherId") REFERENCES "salary_vouchers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_9c177168eb7fa4ff46cb4e90698" FOREIGN KEY ("purchaseQuotationId") REFERENCES "purchase_quotations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_e04bec5cd5b302470c3ae474e1c" FOREIGN KEY ("vendorId") REFERENCES "vendors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_1de7eb246940b05765d2c99a7ec" FOREIGN KEY ("purchaseOrderId") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_f87b1b82a3aff16d1cb5e49a656" FOREIGN KEY ("productId") REFERENCES "vendor_products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_notes" ADD CONSTRAINT "FK_124dbdede40e3ab2d71b1e1cd9c" FOREIGN KEY ("purchaseOrderId") REFERENCES "purchase_orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_notes" ADD CONSTRAINT "FK_c4935c4f6a91546c20ecac25567" FOREIGN KEY ("receivedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_notes" ADD CONSTRAINT "FK_b4b9148eb6b5e12748c5242cb05" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_note_items" ADD CONSTRAINT "FK_9e2d45e78b1a44e572fd461a6a5" FOREIGN KEY ("grnId") REFERENCES "goods_receipt_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_note_items" ADD CONSTRAINT "FK_438e3b39aa3b046925b546725a2" FOREIGN KEY ("productId") REFERENCES "vendor_products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_note_items" ADD CONSTRAINT "FK_52842070e21042323981a3c3335" FOREIGN KEY ("purchaseOrderItemId") REFERENCES "purchase_order_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_inventory_stocks" ADD CONSTRAINT "FK_f35b72258bedbe54f300db28b57" FOREIGN KEY ("productId") REFERENCES "vendor_products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_inventory_batches" ADD CONSTRAINT "FK_1de3262ed507374cf2d8f8b5a6e" FOREIGN KEY ("productId") REFERENCES "vendor_products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_inventory_batches" ADD CONSTRAINT "FK_128f1eed2ed9ec555aaf742c53a" FOREIGN KEY ("grnId") REFERENCES "goods_receipt_notes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_logs" ADD CONSTRAINT "FK_5942ccde8b903032c489b9a38c4" FOREIGN KEY ("productId") REFERENCES "vendor_products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_logs" ADD CONSTRAINT "FK_04a9418f613423853f8af905f7a" FOREIGN KEY ("batchId") REFERENCES "maintenance_inventory_batches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_logs" ADD CONSTRAINT "FK_3e8ccadc174ab01d07dabe29754" FOREIGN KEY ("grnId") REFERENCES "goods_receipt_notes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_logs" ADD CONSTRAINT "FK_a75c464bce48846c50844ce2588" FOREIGN KEY ("jobCardId") REFERENCES "job_cards"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_logs" ADD CONSTRAINT "FK_e7427f4031a6473adcc57e48ff9" FOREIGN KEY ("performedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issues" ADD CONSTRAINT "FK_8b6e22d76e9e9f90a922e9c5479" FOREIGN KEY ("jobCardId") REFERENCES "job_cards"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issues" ADD CONSTRAINT "FK_fc036de1530de9d3c279d57c225" FOREIGN KEY ("issuedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issues" ADD CONSTRAINT "FK_efe494045820d62e0d0cf731919" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issue_items" ADD CONSTRAINT "FK_388c174f5928ac49b2246992f9f" FOREIGN KEY ("stockIssueId") REFERENCES "maintenance_stock_issues"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issue_items" ADD CONSTRAINT "FK_d0338758713e0640e6e097a0f4c" FOREIGN KEY ("productId") REFERENCES "vendor_products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issue_items" ADD CONSTRAINT "FK_9b7bf8c7e30afdb64c0ff42bf37" FOREIGN KEY ("batchId") REFERENCES "maintenance_inventory_batches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issue_items" DROP CONSTRAINT "FK_9b7bf8c7e30afdb64c0ff42bf37"`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issue_items" DROP CONSTRAINT "FK_d0338758713e0640e6e097a0f4c"`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issue_items" DROP CONSTRAINT "FK_388c174f5928ac49b2246992f9f"`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issues" DROP CONSTRAINT "FK_efe494045820d62e0d0cf731919"`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issues" DROP CONSTRAINT "FK_fc036de1530de9d3c279d57c225"`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_issues" DROP CONSTRAINT "FK_8b6e22d76e9e9f90a922e9c5479"`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_logs" DROP CONSTRAINT "FK_e7427f4031a6473adcc57e48ff9"`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_logs" DROP CONSTRAINT "FK_a75c464bce48846c50844ce2588"`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_logs" DROP CONSTRAINT "FK_3e8ccadc174ab01d07dabe29754"`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_logs" DROP CONSTRAINT "FK_04a9418f613423853f8af905f7a"`);
        await queryRunner.query(`ALTER TABLE "maintenance_stock_logs" DROP CONSTRAINT "FK_5942ccde8b903032c489b9a38c4"`);
        await queryRunner.query(`ALTER TABLE "maintenance_inventory_batches" DROP CONSTRAINT "FK_128f1eed2ed9ec555aaf742c53a"`);
        await queryRunner.query(`ALTER TABLE "maintenance_inventory_batches" DROP CONSTRAINT "FK_1de3262ed507374cf2d8f8b5a6e"`);
        await queryRunner.query(`ALTER TABLE "maintenance_inventory_stocks" DROP CONSTRAINT "FK_f35b72258bedbe54f300db28b57"`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_note_items" DROP CONSTRAINT "FK_52842070e21042323981a3c3335"`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_note_items" DROP CONSTRAINT "FK_438e3b39aa3b046925b546725a2"`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_note_items" DROP CONSTRAINT "FK_9e2d45e78b1a44e572fd461a6a5"`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_notes" DROP CONSTRAINT "FK_b4b9148eb6b5e12748c5242cb05"`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_notes" DROP CONSTRAINT "FK_c4935c4f6a91546c20ecac25567"`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_notes" DROP CONSTRAINT "FK_124dbdede40e3ab2d71b1e1cd9c"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_f87b1b82a3aff16d1cb5e49a656"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_1de7eb246940b05765d2c99a7ec"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_e04bec5cd5b302470c3ae474e1c"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_9c177168eb7fa4ff46cb4e90698"`);
        await queryRunner.query(`ALTER TABLE "payslips" DROP CONSTRAINT "FK_228a2b9d8338c0b6f02f314faa7"`);
        await queryRunner.query(`ALTER TABLE "payslips" DROP CONSTRAINT "FK_6d014f9140e2573b815c9ea5f13"`);
        await queryRunner.query(`ALTER TABLE "payslips" DROP CONSTRAINT "FK_3fa0aa64d0a6d751ea49e6cd804"`);
        await queryRunner.query(`ALTER TABLE "payslips" DROP CONSTRAINT "FK_900143f20e6cd2fc0153db2242c"`);
        await queryRunner.query(`ALTER TABLE "payroll_runs" DROP CONSTRAINT "FK_a88d63ececef4f91cc8bc6f2d14"`);
        await queryRunner.query(`ALTER TABLE "payroll_runs" DROP CONSTRAINT "FK_286ecf1480ead4f864cccf944c6"`);
        await queryRunner.query(`ALTER TABLE "payroll_runs" DROP CONSTRAINT "FK_21db0d0b704577d5831f603c9f9"`);
        await queryRunner.query(`ALTER TABLE "employee_salaries" DROP CONSTRAINT "FK_9be022bd97dc15ebf40b2d813fa"`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" DROP CONSTRAINT "FK_cb771ce65ed39c4e6386e23f540"`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" DROP CONSTRAINT "FK_413f2d2b3e6f33e39bb457e239b"`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" DROP CONSTRAINT "FK_85e980ff939978db60fa5f47bee"`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" DROP CONSTRAINT "FK_2fac4cf52da3eefb6be1c0dc721"`);
        await queryRunner.query(`ALTER TABLE "bilty" DROP CONSTRAINT "FK_b0cb3614189b98c4190781025a0"`);
        await queryRunner.query(`ALTER TABLE "bilty" DROP CONSTRAINT "FK_42830f58f73360cfd463791c89a"`);
        await queryRunner.query(`ALTER TABLE "transporter_documents" DROP CONSTRAINT "FK_572d7d58fb3f677dd9697f55ac5"`);
        await queryRunner.query(`ALTER TABLE "transporter_contacts" DROP CONSTRAINT "FK_0f239b0dfa61da1d289e8f6d39e"`);
        await queryRunner.query(`ALTER TABLE "transporters" DROP CONSTRAINT "FK_991bb6962884628500d9976025c"`);
        await queryRunner.query(`ALTER TABLE "transporters" DROP CONSTRAINT "FK_ba965a1211e126539bf77853e82"`);
        await queryRunner.query(`ALTER TABLE "broker_documents" DROP CONSTRAINT "FK_8d568802ba4d4a9d2781ea4ed9f"`);
        await queryRunner.query(`ALTER TABLE "broker_contacts" DROP CONSTRAINT "FK_2065bfdccb7a129fb9eda24b920"`);
        await queryRunner.query(`ALTER TABLE "brokers" DROP CONSTRAINT "FK_c8a80dcab51a56e2cfa12b7eca8"`);
        await queryRunner.query(`ALTER TABLE "brokers" DROP CONSTRAINT "FK_189811cc51835aff7c3ea909bde"`);
        await queryRunner.query(`ALTER TABLE "purchase_quotation_items" DROP CONSTRAINT "FK_3957498131756bb07ceba105bcd"`);
        await queryRunner.query(`ALTER TABLE "purchase_quotation_items" DROP CONSTRAINT "FK_46b622fbc48deb7fc11b7c50310"`);
        await queryRunner.query(`ALTER TABLE "purchase_quotations" DROP CONSTRAINT "FK_20909dfcb24e8f531b21b2a2021"`);
        await queryRunner.query(`ALTER TABLE "purchase_quotations" DROP CONSTRAINT "FK_8121bfe95b8786437223d9972e5"`);
        await queryRunner.query(`ALTER TABLE "job_card_items" DROP CONSTRAINT "FK_5e2f6c1e2dc6351d5233a659c15"`);
        await queryRunner.query(`ALTER TABLE "job_cards" DROP CONSTRAINT "FK_2b22db22210e8c93a93f79d6259"`);
        await queryRunner.query(`ALTER TABLE "job_cards" DROP CONSTRAINT "FK_f08a577bfd99d43be799fab0137"`);
        await queryRunner.query(`ALTER TABLE "job_cards" DROP CONSTRAINT "FK_c7ac66f7c358f2a13d7f883f7ba"`);
        await queryRunner.query(`ALTER TABLE "job_cards" DROP CONSTRAINT "FK_6c60830f6949223bab63f3c6934"`);
        await queryRunner.query(`ALTER TABLE "maintenance_schedules" DROP CONSTRAINT "FK_03aa43143cfbe07ac42b061837e"`);
        await queryRunner.query(`CREATE TYPE "public"."activities_module_enum_old" AS ENUM('USERS_ACCESS', 'FINANCE', 'BILLING', 'TRIPS', 'MARKETPLACE')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "module" TYPE "public"."activities_module_enum_old" USING "module"::"text"::"public"."activities_module_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."activities_module_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."activities_module_enum_old" RENAME TO "activities_module_enum"`);
        await queryRunner.query(`DROP TABLE "maintenance_stock_issue_items"`);
        await queryRunner.query(`DROP TABLE "maintenance_stock_issues"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_stock_issues_status_enum"`);
        await queryRunner.query(`DROP TABLE "maintenance_stock_logs"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_stock_logs_referencetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_stock_logs_movementtype_enum"`);
        await queryRunner.query(`DROP TABLE "maintenance_inventory_batches"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_inventory_batches_status_enum"`);
        await queryRunner.query(`DROP TABLE "maintenance_inventory_stocks"`);
        await queryRunner.query(`DROP TABLE "goods_receipt_note_items"`);
        await queryRunner.query(`DROP TABLE "goods_receipt_notes"`);
        await queryRunner.query(`DROP TYPE "public"."goods_receipt_notes_status_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_order_items"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_order_items_itemtype_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_receivingstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee5bae81f62c8855325c8d6275"`);
        await queryRunner.query(`DROP TABLE "payslips"`);
        await queryRunner.query(`DROP TYPE "public"."payslips_status_enum"`);
        await queryRunner.query(`DROP TABLE "payroll_runs"`);
        await queryRunner.query(`DROP TYPE "public"."payroll_runs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5999386b61122bfeb6f7b748d"`);
        await queryRunner.query(`DROP TABLE "pay_periods"`);
        await queryRunner.query(`DROP TYPE "public"."pay_periods_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9b997acd6c774eb3fbff2aa35"`);
        await queryRunner.query(`DROP TABLE "employee_salaries"`);
        await queryRunner.query(`DROP TYPE "public"."employee_salaries_paytype_enum"`);
        await queryRunner.query(`DROP TABLE "shop"`);
        await queryRunner.query(`DROP TABLE "purchase_quotation_items"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_quotation_items_itemtype_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_quotations"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_quotations_status_enum"`);
        await queryRunner.query(`DROP TABLE "job_card_items"`);
        await queryRunner.query(`DROP TYPE "public"."job_card_items_status_enum"`);
        await queryRunner.query(`DROP TABLE "job_cards"`);
        await queryRunner.query(`DROP TYPE "public"."job_cards_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."job_cards_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."job_cards_maintenancetype_enum"`);
        await queryRunner.query(`DROP TABLE "maintenance_schedules"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_schedules_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_schedules_timeintervalunit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_schedules_triggertype_enum"`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" ADD CONSTRAINT "FK_bilty_freights_createdBy" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" ADD CONSTRAINT "FK_bilty_freights_assetAccId" FOREIGN KEY ("assetAccId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" ADD CONSTRAINT "FK_bilty_freights_brokerId" FOREIGN KEY ("brokerId") REFERENCES "brokers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bilty_freights" ADD CONSTRAINT "FK_bilty_freights_biltyId" FOREIGN KEY ("biltyId") REFERENCES "bilty"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bilty" ADD CONSTRAINT "FK_bilty_transporterId" FOREIGN KEY ("transporterId") REFERENCES "transporters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bilty" ADD CONSTRAINT "FK_bilty_brokerId" FOREIGN KEY ("brokerId") REFERENCES "brokers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transporter_documents" ADD CONSTRAINT "FK_transporter_documents_transporterId" FOREIGN KEY ("transporterId") REFERENCES "transporters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transporter_contacts" ADD CONSTRAINT "FK_transporter_contacts_transporterId" FOREIGN KEY ("transporterId") REFERENCES "transporters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transporters" ADD CONSTRAINT "FK_transporters_cityId" FOREIGN KEY ("cityId") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transporters" ADD CONSTRAINT "FK_transporters_stateId" FOREIGN KEY ("stateId") REFERENCES "states"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "broker_documents" ADD CONSTRAINT "FK_broker_documents_brokerId" FOREIGN KEY ("brokerId") REFERENCES "brokers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "broker_contacts" ADD CONSTRAINT "FK_broker_contacts_brokerId" FOREIGN KEY ("brokerId") REFERENCES "brokers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brokers" ADD CONSTRAINT "FK_brokers_cityId" FOREIGN KEY ("cityId") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brokers" ADD CONSTRAINT "FK_brokers_stateId" FOREIGN KEY ("stateId") REFERENCES "states"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
