/** API-only type for creating postable business accounts (not stored in DB). */
export enum ChartOfAccountType {
  CASH = 'CASH',
  BANK = 'BANK',
  INVENTORY = 'INVENTORY',
  BUSINESS_EXPENSE = 'BUSINESS_EXPENSE',
  BUSINESS_INCOME = 'BUSINESS_INCOME',
  OWNER_CAPITAL = 'OWNER_CAPITAL',
  SALARIES_PAYABLE = 'SALARIES_PAYABLE',
  TAX_PAYABLE = 'TAX_PAYABLE',
  SHORT_TERM_LOAN_PAYABLE = 'SHORT_TERM_LOAN_PAYABLE',
  LONG_TERM_LOAN_PAYABLE = 'LONG_TERM_LOAN_PAYABLE',
}
