import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { JwtModule } from '@nestjs/jwt';
import { PassportModule } from '@nestjs/passport';
import { TypeOrmModule } from '@nestjs/typeorm';
import { buildDatabaseOptions } from './config/database.config';
import { JwtStrategy } from './auth/strategies/jwt.strategy';
import { PermissionGuard } from './auth/guards/permission.guard';
import {
  Activity,
  ChartOfAccount,
  City,
  Client,
  ClientContact,
  ClientDocument,
  ClientDropoffLocation,
  ClientPickupLocation,
  Country,
  Driver,
  DriverDocument,
  PasswordResetToken,
  Permission,
  Role,
  State,
  SystemSetting,
  TaxRule,
  User,
  UserAuthProvider,
  Vehicle,
  VehicleCapacity,
  VehicleDocument,
  VehicleSize,
  VehicleType,
  Vendor,
  VendorCategory,
} from './database/entities';
import {
  AppController,
  AuthController,
  GeoController,
  ProfileController,
  PusherController,
  RolesController,
  SystemSettingController,
  UsersController,
  UtilitiesController,
  VehicleCapacitiesController,
  VehicleSizesController,
  VehicleTypesController,
  VehiclesController,
  VendorsController,
  VendorCategoriesController,
  ActivitiesController,
  DriversController,
  ChartOfAccountsController,
  ClientsController,
  TaxRulesController,
} from './controllers';
import {
  AppService,
  AuthService,
  GeoService,
  MailService,
  PasswordResetTokenService,
  ProfileService,
  PusherService,
  RolesService,
  S3Service,
  SystemSettingService,
  UserAuthProviderService,
  UsersService,
  VehicleCapacitiesService,
  VehicleSizesService,
  VehicleTypesService,
  VehiclesService,
  VendorsService,
  VendorCategoriesService,
  ActivitiesService,
  DriversService,
  ChartOfAccountsService,
  ClientsService,
  TaxRulesService,
} from './services';

@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    TypeOrmModule.forRootAsync({
      inject: [ConfigService],
      useFactory: () => buildDatabaseOptions(),
    }),
    TypeOrmModule.forFeature([
      User,
      Role,
      Permission,
      PasswordResetToken,
      UserAuthProvider,
      Activity,
      Driver,
      DriverDocument,
      Client,
      ClientContact,
      ClientDocument,
      ClientDropoffLocation,
      ClientPickupLocation,
      Vendor,
      VendorCategory,
      Vehicle,
      VehicleType,
      VehicleSize,
      VehicleCapacity,
      VehicleDocument,
      ChartOfAccount,
      Country,
      State,
      City,
      SystemSetting,
      TaxRule,
    ]),
    PassportModule.register({ defaultStrategy: 'jwt' }),
    JwtModule.registerAsync({
      inject: [ConfigService],
      useFactory: (config: ConfigService) => ({
        secret: config.getOrThrow<string>('JWT_SECRET'),
        signOptions: {
          expiresIn: (config.get<string>('JWT_EXPIRES_IN') ??
            '7d') as `${number}d`,
        },
      }),
    }),
  ],
  controllers: [
    AppController,
    AuthController,
    ProfileController,
    PusherController,
    GeoController,
    SystemSettingController,
    VendorsController,
    VendorCategoriesController,
    RolesController,
    UsersController,
    UtilitiesController,
    VehicleTypesController,
    VehicleSizesController,
    VehicleCapacitiesController,
    VehiclesController,
    ActivitiesController,
    DriversController,
    ChartOfAccountsController,
    ClientsController,
    TaxRulesController,
  ],
  providers: [
    AppService,
    AuthService,
    ProfileService,
    UsersService,
    MailService,
    PasswordResetTokenService,
    UserAuthProviderService,
    PusherService,
    S3Service,
    GeoService,
    SystemSettingService,
    VendorsService,
    VendorCategoriesService,
    RolesService,
    VehicleTypesService,
    VehicleSizesService,
    VehicleCapacitiesService,
    VehiclesService,
    ActivitiesService,
    DriversService,
    ChartOfAccountsService,
    ClientsService,
    TaxRulesService,
    JwtStrategy,
    PermissionGuard,
  ],
})
export class AppModule {}
