import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { JwtModule } from '@nestjs/jwt';
import { PassportModule } from '@nestjs/passport';
import { ScheduleModule } from '@nestjs/schedule';
import { TypeOrmModule } from '@nestjs/typeorm';
import { buildDatabaseOptions } from './config/database.config';
import { JwtStrategy } from './auth/strategies/jwt.strategy';
import { PermissionGuard } from './auth/guards/permission.guard';
import {
  Activity,
  Bilty,
  BiltyLoading,
  BiltyOffLoading,
  Trip,
  TripDriver,
  TripUpcountryLoad,
  TripDowncountryLoad,
  TripOfficeExpense,
  TripPumpExpense,
  TripFuelExpense,
  TripMtagExpense,
  TripOtherExpense,
  ChartOfAccount,
  City,
  Client,
  ClientContact,
  ClientDocument,
  ClientDropoffLocation,
  ClientPickupLocation,
  ClientRate,
  ClientRateLog,
  Country,
  Driver,
  DriverDocument,
  AssignedVehicle,
  PasswordResetToken,
  Permission,
  Role,
  State,
  SystemSetting,
  TaxRule,
  User,
  UserAuthProvider,
  Vehicle,
  VehicleCapacity,
  VehicleDocument,
  VehicleSize,
  VehicleType,
  Vendor,
  VendorCategory,
  VendorContact,
  VendorProduct,
  VendorRate,
  VendorRateLog,
  Warehouse,
  Transaction,
} from './database/entities';
import {
  AppController,
  AuthController,
  BiltysController,
  PublicBiltysController,
  TripsController,
  TripDriversController,
  GeoController,
  ProfileController,
  PusherController,
  RolesController,
  SystemSettingController,
  UsersController,
  UtilitiesController,
  VehicleCapacitiesController,
  VehicleSizesController,
  VehicleTypesController,
  VehiclesController,
  VendorsController,
  VendorCategoriesController,
  VendorProductsController,
  VendorRatesController,
  ActivitiesController,
  DriversController,
  AssignedVehiclesController,
  ChartOfAccountsController,
  TransactionsController,
  ClientsController,
  ClientRatesController,
  WarehousesController,
  TaxRulesController,
  DashboardController,
} from './controllers';
import {
  AppService,
  AuthService,
  BiltysService,
  BiltyPdfService,
  TripsService,
  TripDriversService,
  GeoService,
  MailService,
  PasswordResetTokenService,
  ProfileService,
  PusherService,
  RolesService,
  S3Service,
  SystemSettingService,
  UserAuthProviderService,
  UsersService,
  VehicleCapacitiesService,
  VehicleSizesService,
  VehicleTypesService,
  VehiclesService,
  VendorsService,
  VendorCategoriesService,
  VendorProductsService,
  VendorRatesService,
  ActivitiesService,
  DriversService,
  DriverPdfService,
  AssignedVehiclesService,
  ChartOfAccountsService,
  TransactionsService,
  ClientsService,
  ClientRatesService,
  ClientRateFuelAdjustmentService,
  WarehousesService,
  TaxRulesService,
  DashboardService,
} from './services';
@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    ScheduleModule.forRoot(),
    TypeOrmModule.forRootAsync({
      inject: [ConfigService],
      useFactory: () => buildDatabaseOptions(),
    }),
    TypeOrmModule.forFeature([
      User,
      Role,
      Permission,
      PasswordResetToken,
      UserAuthProvider,
      Activity,
      Driver,
      DriverDocument,
      AssignedVehicle,
      Client,
      ClientContact,
      ClientDocument,
      ClientDropoffLocation,
      ClientPickupLocation,
      ClientRate,
      ClientRateLog,
      Warehouse,
      Vendor,
      VendorCategory,
      VendorContact,
      VendorProduct,
      VendorRate,
      VendorRateLog,
      Vehicle,
      VehicleType,
      VehicleSize,
      VehicleCapacity,
      VehicleDocument,
      ChartOfAccount,
      Transaction,
      Country,
      State,
      City,
      SystemSetting,
      TaxRule,
      Bilty,
      BiltyLoading,
      BiltyOffLoading,
      Trip,
      TripDriver,
      TripUpcountryLoad,
      TripDowncountryLoad,
      TripOfficeExpense,
      TripPumpExpense,
      TripFuelExpense,
      TripMtagExpense,
      TripOtherExpense,
    ]),
    PassportModule.register({ defaultStrategy: 'jwt' }),
    JwtModule.registerAsync({
      inject: [ConfigService],
      useFactory: (config: ConfigService) => ({
        secret: config.getOrThrow<string>('JWT_SECRET'),
        signOptions: {
          expiresIn: (config.get<string>('JWT_EXPIRES_IN') ??
            '7d') as `${number}d`,
        },
      }),
    }),
  ],
  controllers: [
    AppController,
    AuthController,
    ProfileController,
    PusherController,
    GeoController,
    SystemSettingController,
    VendorsController,
    VendorCategoriesController,
    VendorProductsController,
    VendorRatesController,
    RolesController,
    UsersController,
    UtilitiesController,
    VehicleTypesController,
    VehicleSizesController,
    VehicleCapacitiesController,
    VehiclesController,
    ActivitiesController,
    DriversController,
    AssignedVehiclesController,
    ChartOfAccountsController,
    TransactionsController,
    ClientsController,
    ClientRatesController,
    WarehousesController,
    TaxRulesController,
    BiltysController,
    PublicBiltysController,
    TripsController,
    TripDriversController,
    DashboardController,
  ],
  providers: [
    AppService,
    AuthService,
    ProfileService,
    UsersService,
    MailService,
    PasswordResetTokenService,
    UserAuthProviderService,
    PusherService,
    S3Service,
    GeoService,
    SystemSettingService,
    VendorsService,
    VendorCategoriesService,
    VendorProductsService,
    VendorRatesService,
    RolesService,
    VehicleTypesService,
    VehicleSizesService,
    VehicleCapacitiesService,
    VehiclesService,
    ActivitiesService,
    DriversService,
    DriverPdfService,
    AssignedVehiclesService,
    ChartOfAccountsService,
    TransactionsService,
    ClientsService,
    ClientRatesService,
    ClientRateFuelAdjustmentService,
    WarehousesService,
    TaxRulesService,
    BiltysService,
    BiltyPdfService,
    TripsService,
    TripDriversService,
    DashboardService,
    JwtStrategy,
    PermissionGuard,
  ],
})
export class AppModule {}
